name: CI Workflow

on: pull_request
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/Checkout@v7

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
